// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(SistemaGestionContext))]
    [Migration("20250909193706_inicio")]
    partial class inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Perez",
                            Direccion = "Praderas 4590",
                            IsDeleted = false,
                            Nombre = "Juan",
                            Telefono = "3498657842"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Borges",
                            Direccion = "Rivadavia 3486",
                            IsDeleted = false,
                            Nombre = "Mario",
                            Telefono = "3498412987"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Morales",
                            Direccion = "Santa Fe 3961",
                            IsDeleted = false,
                            Nombre = "Analia",
                            Telefono = "3498475986"
                        });
                });

            modelBuilder.Entity("Service.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DetallesPedidos");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            Cantidad = 2500,
                            IsDeleted = false,
                            PedidoId = 10,
                            ProductoId = 2500
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 2548,
                            IsDeleted = false,
                            PedidoId = 11,
                            ProductoId = 365
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 4532,
                            IsDeleted = false,
                            PedidoId = 12,
                            ProductoId = 123
                        });
                });

            modelBuilder.Entity("Service.Models.DetallePresupuesto", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PresupuestoId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.ToTable("DetallesPresupuestos");

                    b.HasData(
                        new
                        {
                            IdDetalle = 1,
                            Cantidad = 10,
                            IsDeleted = false,
                            PresupuestoId = 1,
                            ProductoId = 1
                        },
                        new
                        {
                            IdDetalle = 2,
                            Cantidad = 5,
                            IsDeleted = false,
                            PresupuestoId = 2,
                            ProductoId = 2
                        },
                        new
                        {
                            IdDetalle = 3,
                            Cantidad = 8,
                            IsDeleted = false,
                            PresupuestoId = 3,
                            ProductoId = 3
                        });
                });

            modelBuilder.Entity("Service.Models.Mayorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mayoristas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Av. San Martin 1234",
                            Email = "maderaelroble@gmail.com",
                            IsDeleted = false,
                            Nombre = "Fabian Gonzalez",
                            Telefono = "3498657842",
                            TipoProducto = ""
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Av. Siempreviva 2458",
                            Email = "melaminas@gmail.com",
                            IsDeleted = false,
                            Nombre = "Sergio Massa",
                            Telefono = "3498412987",
                            TipoProducto = ""
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "San roque 1257",
                            Email = "antonyeche@gmail.com",
                            IsDeleted = false,
                            Nombre = "Antonio Echeverria",
                            Telefono = "3498425698",
                            TipoProducto = ""
                        });
                });

            modelBuilder.Entity("Service.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pagos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaPago = new DateTime(2025, 9, 9, 16, 37, 1, 745, DateTimeKind.Local).AddTicks(4999),
                            IsDeleted = false,
                            Monto = 15000m,
                            PedidoId = 10,
                            TipoPago = "Tarjeta de Credito"
                        },
                        new
                        {
                            Id = 2,
                            FechaPago = new DateTime(2025, 9, 9, 16, 37, 1, 745, DateTimeKind.Local).AddTicks(5030),
                            IsDeleted = false,
                            Monto = 250000m,
                            PedidoId = 11,
                            TipoPago = "Efectivo"
                        },
                        new
                        {
                            Id = 3,
                            FechaPago = new DateTime(2025, 9, 9, 16, 37, 1, 745, DateTimeKind.Local).AddTicks(5034),
                            IsDeleted = false,
                            Monto = 305000m,
                            PedidoId = 12,
                            TipoPago = "Tarjeta de Débito"
                        });
                });

            modelBuilder.Entity("Service.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            ClienteId = 1,
                            Estado = "En Proceso",
                            Fecha = new DateTime(2025, 9, 9, 16, 37, 1, 745, DateTimeKind.Local).AddTicks(5124),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            ClienteId = 2,
                            Estado = "Completado",
                            Fecha = new DateTime(2025, 9, 9, 16, 37, 1, 745, DateTimeKind.Local).AddTicks(5132),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            ClienteId = 3,
                            Estado = "Pendiente",
                            Fecha = new DateTime(2025, 9, 9, 16, 37, 1, 745, DateTimeKind.Local).AddTicks(5136),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Service.Models.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MontoEstimado")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Presupuestos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            FechaEmision = new DateTime(2025, 9, 9, 16, 37, 1, 745, DateTimeKind.Local).AddTicks(5231),
                            FechaVencimiento = new DateTime(2025, 10, 9, 16, 37, 1, 745, DateTimeKind.Local).AddTicks(5233),
                            IsDeleted = false,
                            MontoEstimado = 50000m
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            FechaEmision = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MontoEstimado = 30500m
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            FechaEmision = new DateTime(2025, 9, 9, 16, 37, 1, 745, DateTimeKind.Local).AddTicks(5262),
                            FechaVencimiento = new DateTime(2025, 10, 9, 16, 37, 1, 745, DateTimeKind.Local).AddTicks(5264),
                            IsDeleted = false,
                            MontoEstimado = 20000m
                        });
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Medida")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Melamina",
                            Descripcion = "Melamina de alta calidad color blanco",
                            IsDeleted = false,
                            Medida = 252,
                            Nombre = "Melamina Blanca",
                            Precio = 0m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Melamina",
                            Descripcion = "Melamina de alta calidad, textura granulada",
                            IsDeleted = false,
                            Medida = 252,
                            Nombre = "Melamina Caoba",
                            Precio = 0m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Melamina",
                            Descripcion = "Melamina de alta calidad, textura mate",
                            IsDeleted = false,
                            Medida = 252,
                            Nombre = "Melamina Negra",
                            Precio = 0m,
                            Stock = 43
                        });
                });

            modelBuilder.Entity("Service.Models.ProductoPresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Medida")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductoPresupuestos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Melamina",
                            Descripcion = "Melamina de alta calidad color blanco",
                            IsDeleted = false,
                            Medida = 252,
                            Nombre = "Melamina Blanca",
                            Precio = 2500m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Melamina",
                            Descripcion = "Melamina de alta calidad, textura granulada",
                            IsDeleted = false,
                            Medida = 252,
                            Nombre = "Melamina Caoba",
                            Precio = 3650m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Melamina",
                            Descripcion = "Melamina de alta calidad, textura mate",
                            IsDeleted = false,
                            Medida = 252,
                            Nombre = "Melamina Negra",
                            Precio = 4230m,
                            Stock = 43
                        });
                });

            modelBuilder.Entity("Service.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 0,
                            Email = "administrador123@gmail.com",
                            IsDeleted = false,
                            Nombre = "admin",
                            Password = "admin123",
                            TipoUsuario = 0
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 0,
                            Email = "sergio2024@gmail.com",
                            IsDeleted = false,
                            Nombre = "sergio cliente",
                            Password = "cliente123",
                            TipoUsuario = 1
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 0,
                            Email = "franquito59@gmail.com",
                            IsDeleted = false,
                            Nombre = "franco cliente",
                            Password = "cliente124",
                            TipoUsuario = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
